### ISSUE TITLE
Inconsistency when using optional collections

### ISSUE THREAD

**Issue by manofthepeace** [smallrye/smallrye-config#940] opened 2023-05-19 19:49 UTC
I have a couple questions related to collection handling in configmapping.

Let say I have this configmapping

```java
@ConfigMapping(prefix = "my")
public interface MyConfig {

    List<Server> servers();

    Map<String, Server> serversMap();

    interface Server {
        String id();

        String name();
    }
}
```

If nothing is configured in any properties/env. The application starts but when an empty list, and a empty map. Question is, it normal? As other properties wont be empty or null, startup will just fail.

In the quarkus doc here https://quarkus.io/guides/config-mappings#collections we can see
`Optional<List<String>> databases();` which works, but then when using it with a custom object like the above example
`Optional<List<Server>> servers();` it fails with the following; 

`java.lang.ClassCastException: class java.util.Optional cannot be cast to class java.util.Collection (java.util.Optional and java.util.Collection are in module java.base of loader 'bootstrap')`

is that normal?  Then I am not exactly sure why have the optional working for String if in any case it is not exactly required, and gets set to an empty list. and unsure why the second variant, with a custom object would fail.

With a map, I get this exception, which is clearer `Caused by: java.lang.IllegalArgumentException: Property type java.util.Optional<java.util.Map<java.lang.String, org.acme.MyConfig$Server>> cannot be optional`. So it kind of make sense to set it to an empty map at startup.

Thanks

**Comment by radcortez** [comment] 2023-05-23 12:21
> If nothing is configured in any properties/env. The application starts but when an empty list, and a empty map. Question is, it normal? As other properties wont be empty or null, startup will just fail.

I understand that it may be inconsistent with other properties. We could make both cases have the same behavior to other properties, but also get some questions we need to answer:

- How do we report back which map key / element index has to exist in the `Map` or `List`?

In this particular example, `my.servers-map.*.id`and `my.servers-map.*.name` represent the matching keys. We could mandate the `Map` to not be empty and throw an error, but how do we know which `Map` key to report to the user that needs to be configured? This is business logic specific since we don't know which keys will be accessed in the `Map`.

A similar thing happens with the `List`, `my.servers[*].id` and `my.servers[*].name` represent the matching keys. This case is a little bit easier since we could mandate for `my.servers[0].id` and `my.servers[0].name` to exist (meaning one element in the `List`).

One additional point on inconsistency is how MicroProfile Config adds support for Arrays / Collections. There is only support for single elements, and the configuration values are set using a comma-separated string. Obviously, this is not suited for Collections of nested elements types. In this case, MicroProfile Config, does mandate the config property to exist, but due to the nature of how it is defined, it is easy to resolve and report to the user.

@dmlloyd any thoughts?

> In the quarkus doc here quarkus doc here https://quarkus.io/guides/config-mappings#collections we can see `Optional<List<String>> databases();` which works, but then when using it with a custom object like the above example `Optional<List<Server>> servers();` it fails with the following;

This should work:
https://github.com/smallrye/smallrye-config/blob/7375af4c56ff6fb59d9574e365a6ad6d271293ba/implementation/src/test/java/io/smallrye/config/ConfigMappingCollectionsTest.java#L188-L218

I've also tried your example and it works for me. Can you provide me with a reproducer?

**Comment by manofthepeace** [comment] 2023-05-23 12:58
Thanks for your reply, for the exception I have created the reproducer here; https://github.com/manofthepeace/configmapping-optional-collection-issue just have to run ./mvnw quarkus:dev

> How do we report back which map key / element index has to exist in the Map or List?

I had the same question in my mind while writing this issue, nothing trivial came to mind. Was wondering if tthere should be like at least 1 element, so it is not null, but then its does not really make much sense, and it is something that probably should be achieved anyway with hibernate validator at this point so really unsure on this.

**Comment by radcortez** [comment] 2023-05-23 14:47
> Thanks for your reply, for the exception I have created the reproducer here; https://github.com/manofthepeace/configmapping-optional-collection-issue just have to run ./mvnw quarkus:dev

Ah! The issue is with BeanValidator. I'll have a look.
 
> I had the same question in my mind while writing this issue, nothing trivial came to mind. Was wondering if tthere should be like at least 1 element, so it is not null, but then its does not really make much sense, and it is something that probably should be achieved anyway with hibernate validator at this point so really unsure on this.

We don't really need Validator for this case, especially because a validator may not even be available to us. While we can force both a `Map` or a `Collection` to contain elements, they may not be the right elements to expect. Maybe we need some way to tell that a certain key in a `Map` or a certain index in a `Collection` must be present. But in that case, shouldn't the mapping just include a single element type (without the enclosing element `Map` or `Collection`)?

**Comment by radcortez** [comment] 2023-05-23 15:02
> > Thanks for your reply, for the exception I have created the reproducer here; https://github.com/manofthepeace/configmapping-optional-collection-issue just have to run ./mvnw quarkus:dev
> 
> Ah! The issue is with BeanValidator. I'll have a look.

This has been fixed in https://github.com/smallrye/smallrye-config/pull/904. But only available in 3.x, not 2.x (as your reproducer). Are you able to upgrade?

**Comment by manofthepeace** [comment] 2023-05-23 15:16
Unfortunately I cannot upgrade at the moment since my project is using an extension from the quarkiverse that hasn't been migrated yet (https://github.com/quarkiverse/quarkus-logging-manager). Good to know this was fixed, in any case I do not need the Optional for the collection as it returns empty and I can easlly check on that, i.e. it does not prevent startup. This issue was more about the inconsistency overall.

>  Maybe we need some way to tell that a certain key in a Map or a certain index in a Collection must be present. But in that case, shouldn't the mapping just include a single element type (without the enclosing element Map or Collection)?

well it depends in our case basically the collection is somewhat mandatory, but it does not have defaults, it needs to be set via k8s env, depending on the deployment. The application can start with the empty collection, but overall the app wont do anything, but via the env, the more things added to the collection, the more the app will do/process in a way. I just thought I neeeded the optional, as the other property will need to to be able to start the aplication without the exception, but then I god the other exception above, and when removing the Optional then I god the empty list, which is ok for me, but not really consistent with the rest.

**Comment by dmlloyd** [comment] 2023-05-23 16:38
> > If nothing is configured in any properties/env. The application starts but when an empty list, and a empty map. Question is, it normal? As other properties wont be empty or null, startup will just fail.
> 
> I understand that it may be inconsistent with other properties. We could make both cases have the same behavior to other properties, but also get some questions we need to answer:
> 
> * How do we report back which map key / element index has to exist in the `Map` or `List`?
> 
> In this particular example, `my.servers-map.*.id`and `my.servers-map.*.name` represent the matching keys. We could mandate the `Map` to not be empty and throw an error, but how do we know which `Map` key to report to the user that needs to be configured? This is business logic specific since we don't know which keys will be accessed in the `Map`.

I think this captures the problem exactly. A list or map can only be "required" if you can define what "required" means for this case. If it can't be a required value then the "required/optional" distinction does not have any meaning.

**Comment by radcortez** [comment] 2023-05-24 15:12
>  This issue was more about the inconsistency overall.

Yes, I think we all agree with this, but making things consistent will create other issues that we don't know how to handle and it will degrade the user experience.

Let's leave it as is.

**Closed by radcortez** 2023-05-24 15:12 UTC
