### ISSUE TITLE
SmallRyeConfigProviderResolver strongly referencing classloaders 

### ISSUE THREAD

**Issue by asoldano** [smallrye/smallrye-config#94] opened 2019-03-22 13:14 UTC
The SmallRyeConfigProviderResolver uses the following map to store the Config for each ClassLoader.

 private Map<ClassLoader,Config> configsForClassLoader = new HashMap<>();

Considering the ConfigProviderResolver instance is held in a static member of ConfigProvider, I believe the map should not keep a strong reference to the its keys, as that could prevent a classloader used as a key there from being garbage collected, effectively resulting in a leak (e.g. in the case of the classloader being the one of a deployment that's re-deployed, or stuff like that).
How about replacing the map with a WeakHashMap?

**Comment by ljnelson** [comment] 2019-05-10 21:03
Lurking, but the only issue I see here is that if a `WeakHashMap` is used, and the classloader referent disappears, then the entry containing the `Config` disappears, and if it is the host for any `Closeable`s (`ConfigSource`s, `Converter`s) that must somehow be closed in some manner as [possibly? mandated by the specification](https://github.com/eclipse/microprofile-config/blob/828ee2fee4ccbef6701943bb96d7be187408fd63/spec/src/main/asciidoc/configprovider.asciidoc), the opportunity to close those things goes away.

To be fair this is a bit hazy as that part of the specification talks about closing `Closeable` `ConfigSource`s and `Converter`s only in the context of `Config`s produced by builders.  On the other hand, this implementation uses builders as part of its production strategy so there you go.

I'm not sure how intentional all of this is but wanted to capture it here.

**Comment by dmlloyd** [comment] 2019-09-27 13:00
Using a weak reference won't solve the problem.  It's possible (likely even) that the config for a given config object will still "leak" because the config contains sources, converters etc. loaded from the class loader key.  The intent is that a config is explicitly released by the container via `ConfigProviderResolver#release` when the corresponding application's class loader disappears.

The spec is unfortunately unclear about whether this causes the config's constituent items to be closed (as well as, for example, what might happen if you register the same config instance on more than one class loader).  That's something that needs a spec issue.  But the original issue here is not a bug and is working as intended.

**Closed by dmlloyd** 2019-09-27 13:00 UTC

**Comment by asoldano** [comment] 2019-09-27 13:18
@dmlloyd thanks for the clarification
